-- ====================================================================
-- Seed: Preguntas adicionales para quiz (modo cuestionario)
-- Se ejecuta tras schema.sql para alcanzar ~8 preguntas por
-- combinación área + dificultad.
-- Cada DO block obtiene el area_id correcto y usa ::jsonb para la columna options.
-- La ausencia de ON CONFLICT requiere que no haya duplicados exactos
-- (el schema.sql ya creó el índice único uq_quiz_question).
-- ====================================================================

-- ─── Frontend ──────────────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'junior', '¿Cuál es la diferencia entre null y undefined en JavaScript?',
    '{"a":"null es un string vacio","b":"null se asigna intencionalmente, undefined indica que no hay valor asignado","c":"Son exactamente iguales","d":"undefined se asigna, null es automatico"}'::jsonb,
    'b', 'null se asigna deliberadamente para indicar "sin valor"; undefined significa que la variable existe pero no tiene valor.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'junior', '¿Qué atributo HTML se usa para proporcionar texto alternativo a una imagen?',
    '{"a":"title","b":"src","c":"alt","d":"href"}'::jsonb,
    'c', 'El atributo alt (alternative text) proporciona una descripcion textual de la imagen para accesibilidad y cuando la imagen no carga.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'junior', '¿Qué es el scope en JavaScript?',
    '{"a":"El ambito donde una variable es accesible","b":"La duracion de una variable en memoria","c":"El tipo de dato de una variable","d":"La cantidad de variables en un programa"}'::jsonb,
    'a', 'El scope (ambito) define la visibilidad y accesibilidad de variables, funciones y objetos en diferentes partes del codigo.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'junior', '¿Cuál es la diferencia entre padding y margin en CSS?',
    '{"a":"Son lo mismo","b":"Padding es el espacio interno entre contenido y borde; margin es el espacio externo fuera del borde","c":"Margin es interno, padding es externo","d":"Padding solo se usa en imagenes"}'::jsonb,
    'b', 'Padding es el espacio interior entre el contenido y el borde del elemento; margin es el espacio exterior que separa el elemento de otros elementos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'junior', '¿Qué metodo de array en JavaScript elimina el ultimo elemento?',
    '{"a":"shift()","b":"pop()","c":"push()","d":"slice()"}'::jsonb,
    'b', 'pop() elimina el ultimo elemento de un array y lo devuelve. shift() elimina el primero, push() agrega al final, slice() extrae una porcion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'junior', '¿Qué significa responsive design?',
    '{"a":"Un diseno que solo funciona en escritorio","b":"Un diseno que se adapta a diferentes tamanos de pantalla","c":"Un diseno con animaciones","d":"Un diseno que carga mas rapido"}'::jsonb,
    'b', 'El responsive design permite que una pagina web se vea y funcione correctamente en diferentes dispositivos y tamanos de pantalla mediante CSS flexible.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'mid', '¿Qué es el hoisting en JavaScript?',
    '{"a":"Una forma de declarar variables","b":"El comportamiento de mover declaraciones al inicio de su ambito durante la compilacion","c":"Un metodo de array","d":"Una propiedad de CSS"}'::jsonb,
    'b', 'Hoisting es el comportamiento de JavaScript donde las declaraciones de variables y funciones se mueven al inicio de su ambito antes de la ejecucion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'mid', '¿Qué son los fragments en React?',
    '{"a":"Componentes de clase","b":"Una forma de agrupar multiples elementos sin agregar nodos extra al DOM","c":"Fragmentos de codigo CSS","d":"Partes de un componente"}'::jsonb,
    'b', 'Los Fragments permiten agrupar una lista de hijos sin agregar nodos extra al DOM, usando <React.Fragment> o la sintaxis <></>.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'mid', '¿Qué hace la propiedad object-fit: cover en CSS?',
    '{"a":"Estira la imagen para llenar el contenedor","b":"Redimensiona la imagen para cubrir el contenedor manteniendo su proporcion","c":"Repite la imagen","d":"Hace la imagen transparente"}'::jsonb,
    'b', 'object-fit: cover redimensiona la imagen para que cubra completamente el contenedor, manteniendo su relacion de aspecto y recortando el exceso si es necesario.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'mid', '¿Qué es el estado (state) en React?',
    '{"a":"Una variable global","b":"Un objeto que representa los datos internos de un componente que cambian y afectan el renderizado","c":"El resultado de una API","d":"Un tipo de componente"}'::jsonb,
    'b', 'El state es un objeto que almacena datos internos del componente. Cuando cambia, React re-renderiza el componente automaticamente.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'mid', '¿Qué son las media queries en CSS?',
    '{"a":"Consultas a la base de datos","b":"Reglas CSS que se aplican segun caracteristicas del dispositivo como el ancho de pantalla","c":"Consultas a APIs externas","d":"Un tipo de fuente"}'::jsonb,
    'b', 'Las media queries permiten aplicar estilos CSS condicionalmente basados en caracteristicas del dispositivo, como el ancho de ventana o resolucion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'mid', '¿Qué es el patron Observer en JavaScript?',
    '{"a":"Un patron donde un objeto mantiene una lista de dependientes que son notificados de cambios","b":"Un metodo de ordenamiento","c":"Una forma de escribir CSS","d":"Un tipo de variable"}'::jsonb,
    'a', 'El patron Observer define una relacion de uno a muchos: cuando el objeto cambia de estado, notifica automaticamente a todos los observadores.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'senior', '¿Qué es el renderizado del lado del servidor (SSR) y que ventajas tiene?',
    '{"a":"Renderizar HTML en el servidor para mejorar SEO y tiempo de carga inicial","b":"Ejecutar JavaScript en el servidor","c":"Usar bases de datos en el servidor","d":"Compilar CSS en el servidor"}'::jsonb,
    'a', 'SSR genera el HTML en el servidor y lo envia al cliente ya renderizado, mejorando el SEO, el rendimiento percibido y la experiencia en dispositivos lentos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'senior', '¿Qué es la accesibilidad web (a11y) y por que es importante?',
    '{"a":"Hacer que los sitios web sean usables por personas con discapacidades","b":"Un framework de CSS","c":"Un metodo de testing","d":"Una herramienta de desarrollo"}'::jsonb,
    'a', 'La accesibilidad web asegura que personas con discapacidades puedan percibir, entender, navegar e interactuar con la web.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'senior', '¿Qué son los Web Workers en JavaScript?',
    '{"a":"Trabajadores de mantenimiento web","b":"Un mecanismo para ejecutar scripts en segundo plano sin bloquear la UI","c":"Una libreria de React","d":"Un tipo de servidor"}'::jsonb,
    'b', 'Web Workers permiten ejecutar codigo JavaScript en un hilo separado del principal, realizando operaciones intensivas sin bloquear la interfaz de usuario.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'senior', '¿Qué es el patron Render Prop en React?',
    '{"a":"Una tecnica para compartir codigo entre componentes usando una prop que retorna JSX","b":"Un metodo de renderizado","c":"Una propiedad de CSS Grid","d":"Un tipo de hook"}'::jsonb,
    'a', 'Render Props es una tecnica donde un componente recibe una funcion como prop que determina que renderizar, permitiendo compartir logica entre componentes.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'senior', '¿Qué es el lazy loading y como se implementa en React?',
    '{"a":"Cargar todos los componentes al inicio","b":"Cargar componentes solo cuando se necesitan, usando React.lazy() y Suspense","c":"Cargar datos de una API","d":"Un metodo de cache"}'::jsonb,
    'b', 'Lazy loading retrasa la carga de componentes no criticos. En React se implementa con React.lazy() y <Suspense> para el fallback.'),
  ((SELECT id FROM technical_areas WHERE name = 'Frontend'), 'senior', '¿Qué es WebSocket y en que se diferencia de HTTP?',
    '{"a":"Un protocolo que permite comunicacion bidireccional en tiempo real","b":"Un metodo HTTP","c":"Una base de datos","d":"Un framework de frontend"}'::jsonb,
    'a', 'WebSocket proporciona un canal de comunicacion full-duplex sobre una unica conexion TCP, permitiendo envio de mensajes en tiempo real.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;

-- ─── Backend ───────────────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'junior', '¿Qué es el metodo HTTP GET y para que se usa?',
    '{"a":"Para crear un nuevo recurso","b":"Para obtener/recuperar datos de un recurso","c":"Para actualizar un recurso","d":"Para eliminar un recurso"}'::jsonb,
    'b', 'GET es el metodo HTTP mas comun, utilizado para solicitar datos de un recurso especifico sin modificar estado.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'junior', '¿Qué es una variable de entorno y por que es importante?',
    '{"a":"Una variable global del sistema usada para configurar aplicaciones","b":"Una variable de JavaScript","c":"Un tipo de base de datos","d":"Un comando de terminal"}'::jsonb,
    'a', 'Las variables de entorno almacenan configuraciones como claves de API y credenciales, manteniendolas fuera del codigo fuente por seguridad.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'junior', '¿Qué es Node.js?',
    '{"a":"Un framework de frontend","b":"Un entorno de ejecucion de JavaScript del lado del servidor","c":"Una base de datos","d":"Un editor de codigo"}'::jsonb,
    'b', 'Node.js es un entorno de ejecucion que permite ejecutar JavaScript en el servidor, basado en el motor V8 de Chrome con I/O sin bloqueo.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'junior', '¿Qué significa el codigo de estado HTTP 404?',
    '{"a":"OK - Solicitud exitosa","b":"No encontrado - El recurso solicitado no existe","c":"Error interno del servidor","d":"No autorizado"}'::jsonb,
    'b', 'HTTP 404 significa que el servidor no pudo encontrar el recurso solicitado. Es uno de los errores HTTP mas comunes.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'junior', '¿Qué es npm en el ecosistema Node.js?',
    '{"a":"Un editor de codigo","b":"El gestor de paquetes por defecto de Node.js","c":"Un framework web","d":"Un lenguaje de programacion"}'::jsonb,
    'b', 'npm (Node Package Manager) es el gestor de paquetes de Node.js que permite instalar y gestionar dependencias de proyectos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'junior', '¿Qué es una funcion callback en JavaScript?',
    '{"a":"Una funcion que recibe a otra funcion como argumento","b":"Una funcion que se ejecuta inmediatamente","c":"Un tipo de variable","d":"Una funcion que no retorna valor"}'::jsonb,
    'a', 'Un callback es una funcion que se pasa como argumento a otra funcion y se ejecuta despues de que ocurra algun evento.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'mid', '¿Qué es el patron Singleton?',
    '{"a":"Un patron que permite crear una unica instancia de una clase","b":"Un metodo de ordenamiento","c":"Una estructura de datos","d":"Un tipo de bucle"}'::jsonb,
    'a', 'El patron Singleton garantiza que una clase tenga solo una instancia y proporciona un punto de acceso global a ella.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'mid', '¿Qué es una API Key y como se usa?',
    '{"a":"Una contrasenia para la base de datos","b":"Un identificador unico que se envia en peticiones para autenticar al cliente","c":"Una clave de cifrado","d":"Un tipo de token JWT"}'::jsonb,
    'b', 'Una API Key identifica al cliente que realiza la peticion. Se envia generalmente en el header Authorization o como parametro de query.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'mid', '¿Qué es la idempotencia en APIs REST?',
    '{"a":"Multiples peticiones identicas tienen el mismo efecto que una sola","b":"La API siempre devuelve el mismo resultado","c":"La peticion se ejecuta instantaneamente","d":"La API no requiere autenticacion"}'::jsonb,
    'a', 'Idempotencia significa que multiples peticiones identicas producen el mismo resultado que una sola. PUT y DELETE son metodos idempotentes.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'mid', '¿Qué es un proxy inverso?',
    '{"a":"Un servidor entre los clientes y los servidores backend","b":"Una base de datos","c":"Un tipo de firewall","d":"Un editor de codigo"}'::jsonb,
    'a', 'Un proxy inverso recibe peticiones de clientes y las reenvia a servidores backend apropiados, proporcionando balanceo de carga y seguridad.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'mid', '¿Qué es JSON?',
    '{"a":"Un lenguaje de programacion","b":"Un formato ligero de intercambio de datos basado en texto","c":"Una base de datos","d":"Un protocolo de red"}'::jsonb,
    'b', 'JSON (JavaScript Object Notation) es un formato de texto para estructurar datos, facil de leer por humanos y de parsear por maquinas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'mid', '¿Qué es el rate limiting y por que es importante?',
    '{"a":"Limitar la velocidad de respuesta del servidor","b":"Controlar el numero de peticiones por cliente en un periodo de tiempo","c":"Reducir el tamano de las respuestas","d":"Medir el rendimiento del servidor"}'::jsonb,
    'b', 'El rate limiting protege las APIs contra abusos limitando cuantas peticiones puede realizar un cliente en un intervalo de tiempo.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'senior', '¿Qué es el patron Saga en microservicios?',
    '{"a":"Un patron para gestionar transacciones distribuidas en microservicios","b":"Un metodo de ordenamiento","c":"Una base de datos","d":"Un framework de testing"}'::jsonb,
    'a', 'El patron Saga gestiona transacciones que abarcan multiples microservicios, ejecutando secuencia de operaciones locales y compensaciones si algo falla.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'senior', '¿Qué es la consistencia eventual (eventual consistency)?',
    '{"a":"Los datos se vuelven consistentes inmediatamente","b":"Si no hay nuevas actualizaciones, todas las lecturas devolveran el ultimo valor actualizado","c":"Los datos nunca son consistentes","d":"La consistencia es opcional"}'::jsonb,
    'b', 'La consistencia eventual es un modelo donde, dado suficiente tiempo sin actualizaciones, todos los nodos del sistema tendran los mismos datos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'senior', '¿Qué es un Circuit Breaker?',
    '{"a":"Un patron que detecta fallos y evita llamadas repetidas a servicios que fallan","b":"Un disyuntor electrico","c":"Un metodo de autenticacion","d":"Un tipo de base de datos"}'::jsonb,
    'a', 'Circuit Breaker monitorea llamadas a servicios externos y, si detecta alta tasa de fallos, abre el circuito para evitar mas llamadas fallidas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'senior', '¿Qué es la inmutabilidad en infraestructura?',
    '{"a":"Los servidores nunca se modifican tras el despliegue, solo se reemplazan","b":"El codigo no puede cambiar","c":"La base de datos es estatica","d":"Las variables son constantes"}'::jsonb,
    'a', 'Infraestructura inmutable significa que los servidores se reemplazan con nuevas instancias en lugar de actualizarse en caliente.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'senior', '¿Qué es el patron Event Sourcing?',
    '{"a":"Almacenar el estado actual en lugar de los cambios","b":"Almacenar todos los cambios de estado como eventos inmutables en secuencia","c":"Una base de datos de eventos","d":"Un framework de frontend"}'::jsonb,
    'b', 'Event Sourcing almacena cada cambio de estado como un evento inmutable, permitiendo reconstruir el estado actual reproduciendo todos los eventos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Backend'), 'senior', '¿Qué es el teorema CAP y que implica?',
    '{"a":"Todo sistema distribuido solo puede garantizar dos de: consistencia, disponibilidad y tolerancia a particiones","b":"Todo sistema debe tener consistencia, atomicidad y persistencia","c":"Un algoritmo de balanceo de carga","d":"Un protocolo de red"}'::jsonb,
    'a', 'El teorema CAP establece que un sistema distribuido no puede garantizar simultaneamente Consistencia, Disponibilidad y Tolerancia a Particiones.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;

-- ─── Bases de Datos ────────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'junior', '¿Qué es una clave foranea?',
    '{"a":"Una clave que identifica un registro de forma unica","b":"Un campo que referencia la clave primaria de otra tabla","c":"Una clave de cifrado","d":"Un tipo de indice"}'::jsonb,
    'b', 'Una foreign key es un campo en una tabla que se relaciona con la clave primaria de otra tabla, estableciendo una relacion entre ambas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'junior', '¿Qué hace la clausula ORDER BY en SQL?',
    '{"a":"Filtra registros","b":"Ordena los resultados de una consulta","c":"Agrupa registros","d":"Une dos tablas"}'::jsonb,
    'b', 'ORDER BY ordena los resultados de una consulta SQL de forma ascendente (ASC) o descendente (DESC) segun una o mas columnas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'junior', '¿Qué es una clave compuesta?',
    '{"a":"Una clave formada por dos o mas columnas","b":"Una clave que contiene numeros y letras","c":"Una clave secundaria","d":"Un indice comprimido"}'::jsonb,
    'a', 'Una clave compuesta (composite key) utiliza dos o mas columnas para identificar de forma unica cada fila en una tabla.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'junior', '¿Para que sirve la clausula WHERE en SQL?',
    '{"a":"Para ordenar resultados","b":"Para filtrar registros segun una condicion","c":"Para agrupar registros","d":"Para unir tablas"}'::jsonb,
    'b', 'WHERE filtra los registros que cumplen una condicion especifica, permitiendo obtener solo los datos relevantes de una consulta.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'junior', '¿Qué es la normalizacion de bases de datos?',
    '{"a":"Un proceso para organizar datos reduciendo redundancia","b":"Un tipo de compresion","c":"Un metodo de cifrado","d":"Un formato de archivo"}'::jsonb,
    'a', 'La normalizacion organiza los datos en tablas para minimizar la redundancia y dependencias, dividiendo tablas grandes en otras mas pequenas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'junior', '¿Cuál es la diferencia entre DELETE y TRUNCATE?',
    '{"a":"DELETE elimina filas y puede tener WHERE, TRUNCATE elimina toda la tabla mas rapido","b":"Son exactamente iguales","c":"TRUNCATE puede usar WHERE, DELETE no","d":"DELETE es mas rapido que TRUNCATE"}'::jsonb,
    'a', 'DELETE elimina filas condicionalmente (con WHERE) y puede ser revertido con ROLLBACK. TRUNCATE elimina todas las filas rapidamente y no se puede deshacer.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'junior', '¿Qué es una vista (VIEW) en SQL?',
    '{"a":"Una tabla fisica","b":"Una consulta almacenada que se comporta como una tabla virtual","c":"Una copia de seguridad","d":"Un tipo de indice"}'::jsonb,
    'b', 'Una VIEW es una tabla virtual basada en el resultado de una consulta SELECT. No almacena datos, solo la definicion de la consulta.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'mid', '¿Qué es un CTE (Common Table Expression)?',
    '{"a":"Una consulta temporal con nombre definida con WITH que se usa dentro de otra consulta","b":"Un tipo de tabla","c":"Una funcion de agregacion","d":"Un indice temporal"}'::jsonb,
    'a', 'Un CTE define una tabla temporal con nombre usando WITH, permitiendo consultas mas legibles y modulares, util para subconsultas complejas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'mid', '¿Qué es el nivel de aislamiento READ COMMITTED?',
    '{"a":"Una transaccion solo ve datos confirmados antes de que empiece","b":"Una transaccion solo ve datos confirmados en el momento de cada consulta","c":"No hay aislamiento","d":"Las transacciones se ejecutan en serie"}'::jsonb,
    'b', 'READ COMMITTED es el nivel por defecto en PostgreSQL. Cada consulta dentro de una transaccion ve los datos confirmados hasta ese momento.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'mid', '¿Qué son las funciones de ventana (window functions)?',
    '{"a":"Funciones que operan sobre un conjunto de filas relacionadas sin agruparlas en una sola salida","b":"Funciones de la interfaz grafica","c":"Un tipo de JOIN","d":"Funciones de agregacion normales"}'::jsonb,
    'a', 'Las window functions realizan calculos sobre un conjunto de filas relacionadas a la fila actual, sin colapsar el resultado como GROUP BY.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'mid', '¿Qué es la desnormalizacion y cuando se usa?',
    '{"a":"Agregar redundancia intencionalmente para mejorar rendimiento de lectura","b":"Eliminar columnas innecesarias","c":"Dividir tablas en mas pequenas","d":"Un proceso automatico de optimizacion"}'::jsonb,
    'a', 'La desnormalizacion introduce redundancia controlada en el esquema para reducir JOINs y mejorar el rendimiento de lecturas en sistemas de alta carga.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'mid', '¿Qué son los indices parciales en PostgreSQL?',
    '{"a":"Indices que solo incluyen un subconjunto de filas segun una condicion WHERE","b":"Indices incompletos","c":"Indices de una sola columna","d":"Indices temporales"}'::jsonb,
    'a', 'Los indices parciales indexan solo las filas que cumplen una condicion especifica, ahorrando espacio y mejorando rendimiento en consultas filtradas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'mid', '¿Cómo se interpreta un plan de ejecucion (EXPLAIN)?',
    '{"a":"Muestra como PostgreSQL ejecutara una consulta, incluyendo costos y metodos de acceso","b":"Muestra el resultado de la consulta","c":"Muestra los datos de la tabla","d":"Muestra los errores de sintaxis"}'::jsonb,
    'a', 'EXPLAIN muestra el plan de ejecucion que PostgreSQL usara para una consulta, incluyendo el costo estimado, metodos de acceso y orden de operaciones.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'mid', '¿Qué es el versionado de esquemas en BD?',
    '{"a":"Gestionar cambios en el esquema de BD de forma controlada con migraciones","b":"Una version de la base de datos","c":"Un tipo de backup","d":"Un sistema de control de versiones"}'::jsonb,
    'a', 'El versionado de esquemas permite aplicar cambios estructurales a la BD de forma incremental, reproducible y con posibilidad de rollback mediante migraciones.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'senior', '¿Qué es la replicacion multi-maestro en PostgreSQL?',
    '{"a":"Varios nodos pueden aceptar escrituras y sincronizarse entre si","b":"Un solo nodo acepta escrituras y los replican","c":"No es posible en PostgreSQL","d":"Un tipo de backup"}'::jsonb,
    'a', 'La replicacion multi-maestro permite que multiples nodos acepten escrituras y sincronicen los cambios entre ellos, mejorando disponibilidad.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'senior', '¿Qué es el sharding horizontal?',
    '{"a":"Distribuir filas de una tabla entre multiples servidores segun una clave","b":"Dividir columnas entre servidores","c":"Crear indices en varias tablas","d":"Un tipo de respaldo"}'::jsonb,
    'a', 'Sharding horizontal divide una tabla grande en fragmentos (shards) distribuyendo las filas entre multiples servidores basado en una clave de particion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'senior', '¿Qué estrategias de backup ante desastres conoces?',
    '{"a":"Full, incremental, diferencial y WAL archiving con Point-in-Time Recovery","b":"Solo backup completo","c":"Duplicar archivos manualmente","d":"Usar RAID como unico backup"}'::jsonb,
    'a', 'Las estrategias incluyen backups completos, incrementales (solo cambios desde ultimo full), diferenciales y WAL archiving que permite Point-in-Time Recovery.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'senior', '¿Cómo manejarias consistencia eventual en sistemas distribuidos?',
    '{"a":"Usando tecnicas como gossip protocol, conflict resolution y read-repair","b":"Ignorando la consistencia","c":"Usando solo una base de datos","d":"Con backups frecuentes"}'::jsonb,
    'a', 'La consistencia eventual se maneja con protocolos de gossip, resolucion de conflictos (CRDT, last-write-wins), read-repair y hinted handoff.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'senior', '¿Cómo optimizar una BD con mas de 100 millones de registros?',
    '{"a":"Usando particionamiento, indices optimizados, materialized views y sharding","b":"Comprimiendo todos los datos","c":"Eliminando indices","d":"Usando solo una tabla"}'::jsonb,
    'a', 'Para grandes volumenes se usa particionamiento de tablas, indices avanzados (BRIN, parciales), materialized views, sharding y optimizacion de consultas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'senior', '¿Qué es VACUUM en PostgreSQL y por que es importante?',
    '{"a":"Recupera espacio ocupado por tuplas muertas y actualiza estadisticas","b":"Limpia la cache del sistema","c":"Elimina tablas temporales","d":"Un comando de mantenimiento de indices"}'::jsonb,
    'a', 'VACUUM recupera espacio de tuplas muertas (versiones de filas obsoletas por MVCC), actualiza estadisticas y evita el bloat de tablas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Bases de Datos'), 'senior', '¿Qué es Change Data Capture (CDC)?',
    '{"a":"Capturar cambios en la BD en tiempo real para replicarlos a otros sistemas","b":"Un tipo de backup","c":"Un metodo de compresion","d":"Una funcion de agregacion"}'::jsonb,
    'a', 'CDC captura y registra cambios (INSERT, UPDATE, DELETE) en una BD en tiempo real, permitiendo replicarlos a otros sistemas como caches, busquedas o data warehouses.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;

-- ─── Algoritmos ────────────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'junior', '¿Qué es un array y como se diferencia de una lista enlazada?',
    '{"a":"Un array tiene tamano fijo y acceso O(1) por indice; lista enlazada crece dinamicamente y acceso O(n)","b":"Son exactamente iguales","c":"La lista enlazada es mas rapida en acceso","d":"El array no puede almacenar datos"}'::jsonb,
    'a', 'Un array almacena elementos en posiciones de memoria contiguas con acceso O(1) por indice. La lista enlazada usa nodos con punteros, acceso O(n).'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'junior', '¿Cómo funciona el ordenamiento burbuja (bubble sort)?',
    '{"a":"Intercambia elementos adyacentes repetidamente hasta ordenar","b":"Divide el array recursivamente","c":"Construye un heap","d":"Usa un pivote para particionar"}'::jsonb,
    'a', 'Bubble sort recorre el array comparando pares adyacentes e intercambiandolos si estan en orden incorrecto, repitiendo hasta que este ordenado.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'junior', '¿Qué es la recursion?',
    '{"a":"Una funcion que se llama a si misma","b":"Un tipo de bucle","c":"Una estructura de datos","d":"Un metodo de ordenamiento"}'::jsonb,
    'a', 'La recursion es una tecnica donde una funcion se llama a si misma para resolver un problema dividiendolo en subproblemas mas pequenos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'junior', '¿Qué diferencia hay entre Set y Map?',
    '{"a":"Set almacena valores unicos sin clave; Map almacena pares clave-valor","b":"Son iguales","c":"Map almacena solo numeros","d":"Set usa claves duplicadas"}'::jsonb,
    'a', 'Set es una coleccion de valores unicos sin orden. Map es una coleccion de pares clave-valor donde cada clave es unica.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'junior', '¿Cómo funciona la busqueda lineal?',
    '{"a":"Recorre cada elemento hasta encontrar el objetivo, complejidad O(n)","b":"Divide el array en mitades","c":"Usa un hash table","d":"Ordena primero y luego busca"}'::jsonb,
    'a', 'La busqueda lineal examina cada elemento de la lista en orden hasta encontrar el valor buscado o llegar al final. Complejidad O(n).'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'junior', '¿Qué es una hash table y como funciona?',
    '{"a":"Una estructura que almacena pares clave-valor usando una funcion hash para acceso rapido","b":"Una tabla de multiplicar","c":"Un tipo de array","d":"Una funcion matematica"}'::jsonb,
    'a', 'Una hash table usa una funcion hash para convertir la clave en un indice donde almacenar el valor, permitiendo insercion y busqueda en O(1) promedio.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'mid', '¿Cómo funciona MergeSort y cual es su complejidad?',
    '{"a":"Divide el array en mitades, ordena cada una recursivamente y las mezcla; O(n log n)","b":"Intercambia elementos adyacentes; O(n^2)","c":"Usa un pivote; O(n^2) peor caso","d":"Construye un heap; O(n log n)"}'::jsonb,
    'a', 'MergeSort divide recursivamente el array en mitades, las ordena y las fusiona. Complejidad O(n log n) en todos los casos. Estable.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'mid', '¿Qué diferencia hay entre BFS y DFS?',
    '{"a":"BFS explora por niveles con cola; DFS explora por profundidad con pila","b":"BFS usa pila, DFS usa cola","c":"Son identicos","d":"BFS es mas profundo que DFS"}'::jsonb,
    'a', 'BFS (Breadth-First Search) explora el grafo por niveles usando una cola. DFS (Depth-First Search) explora hasta el final de cada rama usando una pila.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'mid', '¿Qué es la tecnica de two pointers?',
    '{"a":"Usar dos punteros que recorren una estructura desde diferentes posiciones","b":"Una funcion con dos parametros","c":"Dos variables globales","d":"Un tipo de arbol binario"}'::jsonb,
    'a', 'Two pointers usa dos indices que recorren un array desde diferentes puntos (principio/fin, ambos al inicio) para resolver problemas eficientemente.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'mid', '¿Qué es un Trie (arbol de prefijos)?',
    '{"a":"Un arbol donde cada nodo representa un prefijo, usado para busquedas de cadenas","b":"Un arbol binario de busqueda","c":"Un heap","d":"Una cola de prioridad"}'::jsonb,
    'a', 'Un Trie almacena cadenas en un arbol donde cada nodo representa un prefijo comun, permitiendo busquedas eficientes de palabras y prefijos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'mid', '¿Qué es el principio de localidad en cache?',
    '{"a":"Los programas tienden a acceder a datos cercanos en tiempo y espacio","b":"La memoria mas rapida esta mas cerca del procesador","c":"Una regla de optimizacion SQL","d":"Un algoritmo de ordenamiento"}'::jsonb,
    'a', 'El principio de localidad establece que los programas acceden frecuentemente a las mismas direcciones (temporal) o direcciones cercanas (espacial).'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'mid', '¿Cómo funciona Insertion Sort y su complejidad?',
    '{"a":"Inserta cada elemento en su posicion correcta entre los ya ordenados; O(n^2)","b":"Divide y conquista; O(n log n)","c":"Intercambia pares; O(n^2)","d":"Construye un heap; O(n log n)"}'::jsonb,
    'a', 'Insertion Sort construye la salida ordenada insertando cada nuevo elemento en la posicion correcta dentro de la parte ya ordenada. O(n^2) peor caso.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'mid', '¿Qué son los algoritmos voraces (greedy)?',
    '{"a":"Algoritmos que toman la mejor decision local en cada paso esperando optimo global","b":"Algoritmos que prueban todas las combinaciones","c":"Algoritmos aleatorios","d":"Algoritmos de ordenamiento"}'::jsonb,
    'a', 'Los algoritmos greedy toman la mejor opcion disponible en cada paso, asumiendo que lleva a la solucion optima global (no siempre funciona).'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'senior', '¿Que es el problema de la subsecuencia comun mas larga (LCS)?',
    '{"a":"Encontrar la secuencia mas larga que aparece en el mismo orden en dos cadenas","b":"Encontrar el elemento mas repetido","c":"Ordenar caracteres","d":"Buscar un patron"}'::jsonb,
    'a', 'LCS encuentra la subsecuencia mas larga comun a dos cadenas. Se resuelve con programacion dinamica en O(n*m).'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'senior', '¿Cómo funciona el algoritmo A* para busqueda de caminos?',
    '{"a":"Usa una heuristica para estimar el costo restante y encontrar la ruta mas corta eficientemente","b":"Explora todas las rutas posibles","c":"Usa solo la distancia real","d":"Es una variante de Dijkstra sin heuristica"}'::jsonb,
    'a', 'A* combina el costo real desde el inicio con una heuristica que estima el costo restante, encontrando la ruta mas corta mas eficientemente que Dijkstra.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'senior', '¿Qué es la tecnica de ventana deslizante (sliding window)?',
    '{"a":"Mantener una ventana de elementos consecutivos que se desliza por la estructura","b":"Una animacion CSS","c":"Un metodo de ordenamiento","d":"Una estructura de datos"}'::jsonb,
    'a', 'Sliding window mantiene un subconjunto contiguo de elementos que se desplaza por la estructura, eficiente para problemas de subarrays/subcadenas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'senior', '¿Cómo funciona el algoritmo de Floyd-Warshall?',
    '{"a":"Encuentra caminos mas cortos entre todos los pares de nodos en un grafo","b":"Ordena elementos en un array","c":"Busca en un arbol binario","d":"Calcula el arbol de expansion minima"}'::jsonb,
    'a', 'Floyd-Warshall calcula las distancias mas cortas entre todos los pares de vertices en un grafo ponderado, usando programacion dinamica O(V^3).'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'senior', '¿Qué es la complejidad amortizada?',
    '{"a":"El tiempo promedio de una operacion en el peor caso, considerando secuencia de operaciones","b":"El tiempo promedio de todas las operaciones","c":"El mejor caso posible","d":"Un tipo de notacion Big O"}'::jsonb,
    'a', 'La complejidad amortizada analiza el costo promedio por operacion en una secuencia, donde algunas operaciones costosas se compensan con muchas baratas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'senior', '¿Qué es un sistema de recomendacion basado en contenido?',
    '{"a":"Recomienda items similares a los que el usuario ha valorado positivamente basado en atributos","b":"Recomienda lo que otros usuarios similares prefieren","c":"Recomienda items aleatorios","d":"Recomienda solo los mas populares"}'::jsonb,
    'a', 'El filtrado basado en contenido recomienda items con atributos similares a los que el usuario ha preferido en el pasado, usando vectores de caracteristicas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Algoritmos'), 'senior', '¿Qué es el backtesting de algoritmos?',
    '{"a":"Evaluar un algoritmo con datos historicos para medir su rendimiento antes de usarlo en produccion","b":"Probar un algoritmo en un entorno de desarrollo","c":"Depurar errores de codigo","d":"Un tipo de testing unitario"}'::jsonb,
    'a', 'Backtesting simula un algoritmo con datos pasados para evaluar su rendimiento y robustez antes de implementarlo en un entorno real.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;

-- ─── Cloud & DevOps ────────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es la computacion en la nube (cloud computing)?',
    '{"a":"Ejecutar aplicaciones en servidores locales","b":"Acceso bajo demanda a recursos informaticos a traves de internet","c":"Un tipo de base de datos","d":"Un editor de codigo en linea"}'::jsonb,
    'b', 'Cloud computing proporciona recursos como servidores, almacenamiento y bases de datos bajo demanda por internet, pagando solo por lo que se usa.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es una maquina virtual en la nube?',
    '{"a":"Un servidor fisico dedicado","b":"Una emulacion de un sistema de computo que ejecuta un SO sobre un hipervisor","c":"Un contenedor ligero","d":"Una aplicacion web"}'::jsonb,
    'b', 'Una maquina virtual virtualiza hardware permitiendo ejecutar un sistema operativo completo sobre un hipervisor, con recursos aislados y dedicados.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es un contenedor en Docker?',
    '{"a":"Una maquina virtual completa","b":"Una unidad estandar de software que empaqueta codigo y dependencias","c":"Un tipo de servidor","d":"Una base de datos"}'::jsonb,
    'b', 'Un contenedor Docker empaqueta una aplicacion con todas sus dependencias, garantizando que funcione igual en cualquier entorno que ejecute Docker.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es un pipeline CI/CD?',
    '{"a":"Un conjunto de pasos automatizados para integrar, probar y desplegar codigo","b":"Una tuberia de datos","c":"Un tipo de red","d":"Un metodo de programacion"}'::jsonb,
    'a', 'CI/CD automatiza la integracion continua (compilacion y pruebas) y la entrega/despliegue continuo, permitiendo lanzamientos frecuentes y confiables.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es AWS S3?',
    '{"a":"Un servidor de bases de datos","b":"Un servicio de almacenamiento de objetos escalable","c":"Un balanceador de carga","d":"Un servicio de DNS"}'::jsonb,
    'b', 'Amazon S3 (Simple Storage Service) es un servicio de almacenamiento de objetos que ofrece escalabilidad, disponibilidad y seguridad para cualquier cantidad de datos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es un balanceador de carga?',
    '{"a":"Un dispositivo que distribuye trafico entre multiples servidores","b":"Un servidor que almacena datos","c":"Una base de datos","d":"Un firewall"}'::jsonb,
    'a', 'Un balanceador de carga distribuye el trafico entrante entre varios servidores backend, mejorando disponibilidad, escalabilidad y tolerancia a fallos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es GitHub Actions?',
    '{"a":"Un editor de codigo","b":"Una plataforma de CI/CD integrada en GitHub","c":"Una base de datos","d":"Un lenguaje de programacion"}'::jsonb,
    'b', 'GitHub Actions permite automatizar flujos de trabajo de CI/CD directamente desde repositorios de GitHub, incluyendo builds, tests y deploys.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'junior', '¿Qué es la infraestructura como codigo (IaC)?',
    '{"a":"Escribir codigo para gestionar y aprovisionar infraestructura en lugar de hacerlo manualmente","b":"Una forma de programar servidores","c":"Un lenguaje de programacion para la nube","d":"Un tipo de base de datos"}'::jsonb,
    'a', 'IaC gestiona la infraestructura (servidores, redes, etc.) mediante archivos de configuracion declarativos, permitiendo versionado, revision y automatizacion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'mid', '¿Qué es Kubernetes y para que sirve?',
    '{"a":"Un orquestador de contenedores que automatiza despliegue, escalado y gestion","b":"Una base de datos","c":"Un editor de codigo","d":"Un servidor web"}'::jsonb,
    'a', 'Kubernetes (K8s) automatiza el despliegue, escalado y operacion de contenedores en clusters, facilitando la gestion de aplicaciones en produccion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'mid', '¿Qué es un Pod en Kubernetes?',
    '{"a":"La unidad minima desplegable que contiene uno o mas contenedores","b":"Un grupo de servidores","c":"Una red virtual","d":"Un volumen de almacenamiento"}'::jsonb,
    'a', 'Un Pod es la unidad mas pequena en Kubernetes. Contiene uno o mas contenedores que comparten red y almacenamiento, ejecutandose juntos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'mid', '¿Qué es Terraform?',
    '{"a":"Una herramienta de IaC que permite definir y aprovisionar infraestructura declarativamente","b":"Una base de datos","c":"Un lenguaje de scripting","d":"Un servidor web"}'::jsonb,
    'a', 'Terraform permite definir infraestructura como codigo usando un lenguaje declarativo (HCL), gestionando recursos en multiples proveedores cloud.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'mid', '¿Qué es el monitoreo con Prometheus?',
    '{"a":"Un sistema de monitoreo y alerta que recolecta metricas de sistemas y servicios","b":"Un editor de texto","c":"Una base de datos SQL","d":"Un lenguaje de programacion"}'::jsonb,
    'a', 'Prometheus es un sistema de monitoreo open-source que recolecta metricas de aplicaciones y servidores, permitiendo consultas, alertas y visualizaciones.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'mid', '¿Qué es un deployment blue-green?',
    '{"a":"Una estrategia que usa dos entornos (azul y verde) para minimizar el downtime en despliegues","b":"Un tipo de base de datos","c":"Un esquema de colores CSS","d":"Un metodo de testing"}'::jsonb,
    'a', 'Blue-green deployment mantiene dos entornos identicos. El trafico se redirige del entorno azul al verde despues de validar el nuevo despliegue.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'mid', '¿Qué es un Load Balancer en AWS?',
    '{"a":"Un servicio que distribuye automaticamente el trafico entre multiples instancias","b":"Un servidor de archivos","c":"Una base de datos","d":"Un servicio de DNS"}'::jsonb,
    'a', 'El Elastic Load Balancer (ELB) de AWS distribuye el trafico entrante entre multiples targets (EC2, contenedores, IPs) en una o mas zonas de disponibilidad.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'mid', '¿Qué es un Dockerfile?',
    '{"a":"Un archivo de texto con instrucciones para construir una imagen Docker","b":"Un archivo de configuracion de red","c":"Un archivo de base de datos","d":"Un archivo de log"}'::jsonb,
    'a', 'Un Dockerfile es un script con instrucciones paso a paso (FROM, RUN, COPY, CMD) para construir automaticamente una imagen Docker reproducible.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'senior', '¿Qué es el patron Sidecar en Kubernetes?',
    '{"a":"Un contenedor auxiliar que extiende o mejora la funcionalidad del contenedor principal en el mismo Pod","b":"Un tipo de balanceador","c":"Una motocicleta con sidecar","d":"Un metodo de despliegue"}'::jsonb,
    'a', 'El patron Sidecar despliega un contenedor auxiliar junto al principal en el mismo Pod, proporcionando funcionalidades como logging, proxy o monitoreo.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'senior', '¿Qué es una Service Mesh?',
    '{"a":"Una capa de infraestructura dedicada para gestionar comunicacion entre servicios","b":"Una red de servidores","c":"Un tipo de base de datos","d":"Un balanceador de carga"}'::jsonb,
    'a', 'Service Mesh gestiona la comunicacion entre microservicios proporcionando descubrimiento, balanceo, cifrado, observabilidad y control de trafico.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'senior', '¿Qué es el escalado horizontal y vertical?',
    '{"a":"Horizontal: agregar mas instancias. Vertical: aumentar recursos de una instancia","b":"Son lo mismo","c":"Horizontal es mas barato que vertical","d":"Vertical agrega mas instancias"}'::jsonb,
    'a', 'El escalado horizontal agrega mas nodos al sistema, mientras que el vertical aumenta los recursos (CPU, RAM) de los nodos existentes.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'senior', '¿Qué es GitOps?',
    '{"a":"Usar Git como fuente unica de verdad para declarar el estado deseado de la infraestructura","b":"Un curso de Git","c":"Un tipo de repositorio","d":"Una herramienta de CI/CD"}'::jsonb,
    'a', 'GitOps utiliza repositorios Git como fuente unica de verdad para la infraestructura, con cambios aplicados automaticamente mediante operadores.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'senior', '¿Qué es un Service Account en Kubernetes?',
    '{"a":"Una identidad para Pods que permite autenticarse ante la API de Kubernetes","b":"Una cuenta de servicio en la nube","c":"Un tipo de Pod","d":"Un usuario humano"}'::jsonb,
    'a', 'Un Service Account proporciona una identidad para que los Pods se autentiquen ante el API server de Kubernetes y accedan a recursos autorizados.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'senior', '¿Qué es el patron Ambassador en microservicios?',
    '{"a":"Un proxy que abstrae la comunicacion con servicios externos","b":"Un embajador diplomatico","c":"Un tipo de contenedor","d":"Un metodo de autenticacion"}'::jsonb,
    'a', 'El patron Ambassador despliega un contenedor proxy que maneja la comunicacion con servicios externos, como conexiones a BD o APIs de terceros.'),
  ((SELECT id FROM technical_areas WHERE name = 'Cloud & DevOps'), 'senior', '¿Qué es Canary Deployment?',
    '{"a":"Desplegar una nueva version solo a un pequeno porcentaje de usuarios para probarla","b":"Un despliegue completo","c":"Un tipo de contenedor","d":"Un metodo de backup"}'::jsonb,
    'a', 'Canary deployment expone la nueva version solo a un subconjunto de usuarios, monitoreando su comportamiento antes de extenderla al resto.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;

-- ─── Ciencia de Datos ──────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'junior', '¿Qué es NumPy en Python?',
    '{"a":"Una libreria para computacion numerica con arrays multidimensionales","b":"Una libreria de visualizacion","c":"Un framework web","d":"Un gestor de paquetes"}'::jsonb,
    'a', 'NumPy proporciona arrays multidimensionales eficientes y funciones matematicas de alto nivel para operar sobre ellos, fundamental en data science.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'junior', '¿Qué es un DataFrame en pandas?',
    '{"a":"Una estructura de datos bidimensional etiquetada, similar a una hoja de calculo","b":"Una matriz numerica","c":"Una tabla en una BD","d":"Un grafico de datos"}'::jsonb,
    'a', 'Un DataFrame es una estructura de datos tabular con filas y columnas etiquetadas, que puede contener diferentes tipos de datos por columna.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'junior', '¿Qué es la estadistica descriptiva?',
    '{"a":"Resumir y describir caracteristicas de un conjunto de datos","b":"Hacer predicciones sobre una poblacion","c":"Probar hipotesis causales","d":"Entrenar modelos de ML"}'::jsonb,
    'a', 'La estadistica descriptiva resume datos mediante medidas como media, mediana, moda, desviacion estandar, cuartiles y visualizaciones.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'junior', '¿Qué es una variable categorica?',
    '{"a":"Una variable que representa categorias o grupos, como colores o tipos","b":"Una variable numerica continua","c":"Una variable booleana","d":"Una variable dependiente"}'::jsonb,
    'a', 'Las variables categoricas representan datos que se dividen en grupos o categorias, como genero, pais o tipo de producto.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'junior', '¿Qué es Matplotlib?',
    '{"a":"Una libreria de Python para crear visualizaciones estaticas, animadas e interactivas","b":"Un lenguaje de consultas","c":"Una base de datos","d":"Un framework de ML"}'::jsonb,
    'a', 'Matplotlib es la libreria fundamental de visualizacion en Python, permitiendo crear graficos de lineas, barras, dispersion, histogramas y mas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'junior', '¿Qué es una correlacion entre variables?',
    '{"a":"Una medida de la relacion lineal entre dos variables","b":"La causa de un fenomeno","c":"Un tipo de grafico","d":"La media de dos variables"}'::jsonb,
    'a', 'La correlacion mide la fuerza y direccion de la relacion lineal entre dos variables, con valores entre -1 y +1.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'junior', '¿Qué es un histograma?',
    '{"a":"Un grafico que agrupa datos numericos en intervalos para mostrar su distribucion","b":"Un grafico de barras","c":"Un grafico de dispersion","d":"Una tabla de frecuencias"}'::jsonb,
    'a', 'Un histograma muestra la distribucion de datos numericos dividiendolos en intervalos (bins) y mostrando la frecuencia de cada intervalo con barras.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'mid', '¿Qué es el feature engineering?',
    '{"a":"Crear y transformar variables a partir de los datos para mejorar modelos ML","b":"Disenar la arquitectura de red","c":"Un tipo de modelo","d":"Una libreria de Python"}'::jsonb,
    'a', 'Feature engineering crea nuevas caracteristicas o transforma las existentes para mejorar el rendimiento de los modelos de machine learning.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'mid', '¿Qué diferencia hay entre regresion y clasificacion?',
    '{"a":"Regresion predice valores continuos, clasificacion predice categorias discretas","b":"Son lo mismo","c":"Clasificacion es supervisada, regresion no","d":"Regresion solo funciona con dos variables"}'::jsonb,
    'a', 'La regresion predice valores numericos continuos (precio, temperatura) mientras que la clasificacion asigna instancias a categorias discretas (spam/no spam).'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'mid', '¿Qué es el teorema de Bayes?',
    '{"a":"Describe la probabilidad de un evento basado en conocimiento previo de condiciones relacionadas","b":"Un teorema de limites","c":"Una formula de calculo","d":"Un teorema de algebra lineal"}'::jsonb,
    'a', 'El teorema de Bayes calcula la probabilidad condicional de un evento dado otro, actualizando creencias previas con nueva evidencia.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'mid', '¿Qué es el sesgo en machine learning?',
    '{"a":"Error por suposiciones demasiado simples en el modelo, llevando a underfitting","b":"Error por exceso de complejidad","c":"Un tipo de dato","d":"Una metrica de evaluacion"}'::jsonb,
    'a', 'El sesgo (bias) es el error introducido por aproximar un problema complejo con un modelo demasiado simple. Alto sesgo causa underfitting.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'mid', '¿Qué es la matriz de confusion?',
    '{"a":"Una tabla que resume el rendimiento de un clasificador comparando predicciones con reales","b":"Una matriz numerica","c":"Un tipo de grafico","d":"Una base de datos"}'::jsonb,
    'a', 'La matriz de confusion muestra verdaderos positivos, falsos positivos, verdaderos negativos y falsos negativos, permitiendo calcular precision, recall y F1.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'mid', '¿Qué es el clustering?',
    '{"a":"Una tecnica no supervisada que agrupa instancias similares sin etiquetas previas","b":"Un tipo de clasificacion supervisada","c":"Un metodo de regresion","d":"Una libreria de Python"}'::jsonb,
    'a', 'El clustering agrupa datos en clusters donde los elementos del mismo grupo son mas similares entre si que con los de otros grupos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'mid', '¿Qué es la validacion cruzada (cross-validation)?',
    '{"a":"Dividir datos en k particiones y entrenar/evaluar el modelo k veces","b":"Validar datos con un solo conjunto de prueba","c":"Un tipo de modelo","d":"Una metrica de error"}'::jsonb,
    'a', 'Cross-validation divide los datos en k subconjuntos, entrena con k-1 y evalua con el restante, repitiendo k veces para una evaluacion robusta.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es el gradiente descendente (gradient descent)?',
    '{"a":"Un algoritmo de optimizacion que minimiza la funcion de error ajustando parametros iterativamente","b":"Un tipo de ascensor","c":"Un metodo de clasificacion","d":"Una libreria de visualizacion"}'::jsonb,
    'a', 'Gradient descent calcula el gradiente de la funcion de error respecto a los parametros y los ajusta en direccion opuesta al gradiente para minimizar el error.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es la maldicion de la dimensionalidad?',
    '{"a":"A medida que aumentan las dimensiones, los datos se vuelven dispersos y los modelos requieren mas muestras","b":"Un problema con muchas variables","c":"Un error de programacion","d":"Un tipo de grafico"}'::jsonb,
    'a', 'La maldicion de la dimensionalidad describe como el aumento de caracteristicas hace que los datos sean mas dispersos, requiriendo exponencialmente mas muestras.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es el balanceo de clases en clasificacion?',
    '{"a":"Tecnicas para manejar datasets donde una clase tiene muchos mas ejemplos que otra","b":"Igualar la cantidad de caracteristicas","c":"Un metodo de normalizacion","d":"Un tipo de algoritmo"}'::jsonb,
    'a', 'El balanceo de clases aborda datasets desbalanceados usando tecnicas como sobremuestreo (SMOTE), submuestreo o pesos de clase ajustados.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es el teorema del limite central?',
    '{"a":"La distribucion de las medias muestrales tiende a una distribucion normal al aumentar el tamano de muestra","b":"Un teorema de calculo","c":"Una propiedad de variables aleatorias","d":"Un teorema de probabilidad basica"}'::jsonb,
    'a', 'El teorema del limite central establece que la distribucion de las medias de muestras independientes tiende a una normal, independientemente de la distribucion original.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es el Analisis de Componentes Principales (PCA)?',
    '{"a":"Reduce la dimensionalidad transformando variables correlacionadas en no correlacionadas","b":"Un metodo de clasificacion","c":"Una prueba estadistica","d":"Un tipo de regresion"}'::jsonb,
    'a', 'PCA reduce la dimensionalidad encontrando nuevas variables (componentes principales) que capturan la maxima varianza de los datos originales.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es Random Forest?',
    '{"a":"Un ensemble de arboles de decision que promedia sus predicciones para mejorar precision","b":"Un bosque aleatorio","c":"Un tipo de red neuronal","d":"Un metodo de clustering"}'::jsonb,
    'a', 'Random Forest construye multiples arboles de decision con muestras y caracteristicas aleatorias, combinando predicciones para reducir overfitting y mejorar precision.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es el procesamiento de lenguaje natural (NLP)?',
    '{"a":"Un campo de IA que permite a las maquinas entender, interpretar y generar lenguaje humano","b":"Un tipo de base de datos","c":"Un lenguaje de programacion","d":"Un metodo de compresion"}'::jsonb,
    'a', 'NLP combina linguistica computacional con ML para procesar y analizar grandes cantidades de datos de lenguaje natural, como texto y voz.'),
  ((SELECT id FROM technical_areas WHERE name = 'Ciencia de Datos'), 'senior', '¿Qué es una red neuronal LSTM?',
    '{"a":"Una red recurrente con compuertas que captura dependencias de largo plazo en secuencias","b":"Una red convolucional","c":"Un algoritmo de optimizacion","d":"Una tecnica de regularizacion"}'::jsonb,
    'a', 'LSTM (Long Short-Term Memory) es una arquitectura de red recurrente que puede aprender dependencias de largo plazo evitando el desvanecimiento del gradiente.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;

-- ─── Desarrollo Móvil ─────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es React Native?',
    '{"a":"Un framework para crear apps moviles nativas usando JavaScript y React","b":"Un tipo de base de datos","c":"Un editor de codigo","d":"Un servidor web"}'::jsonb,
    'a', 'React Native permite desarrollar aplicaciones moviles multiplataforma (iOS y Android) usando componentes React que se renderizan con vistas nativas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es un emulador en desarrollo movil?',
    '{"a":"Un software que simula un dispositivo movil en el ordenador para pruebas","b":"Un dispositivo fisico","c":"Un tipo de compilador","d":"Una base de datos"}'::jsonb,
    'a', 'Un emulador replica el hardware y SO de un dispositivo movil en el ordenador, permitiendo probar apps sin necesidad de dispositivos fisicos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es el ciclo de vida de una app movil?',
    '{"a":"Los estados por los que pasa una app desde que se lanza hasta que se cierra","b":"La duracion de la bateria","c":"El tiempo de desarrollo","d":"La version del SO"}'::jsonb,
    'a', 'El ciclo de vida de una app movil incluye estados como lanzamiento, ejecucion en primer/segundo plano, pausa, reanudacion y terminacion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es una API en el contexto movil?',
    '{"a":"Una interfaz que permite a la app comunicarse con servidores externos","b":"Un tipo de pantalla","c":"Un componente de UI","d":"Un gesto tactil"}'::jsonb,
    'a', 'Las APIs permiten que las apps moviles se comuniquen con servicios backend para obtener o enviar datos, usualmente via HTTP/S.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es el almacenamiento local en una app movil?',
    '{"a":"Guardar datos en el dispositivo del usuario para acceso sin conexion","b":"Almacenar en la nube","c":"La memoria RAM del dispositivo","d":"La cache del navegador"}'::jsonb,
    'a', 'El almacenamiento local (AsyncStorage, SQLite, SharedPreferences) permite persistir datos en el dispositivo para usarlos sin conexion a internet.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es una notificacion push?',
    '{"a":"Un mensaje que aparece en el dispositivo del usuario incluso cuando la app no esta abierta","b":"Un evento tactil","c":"Un tipo de animacion","d":"Un gesto de deslizamiento"}'::jsonb,
    'a', 'Las notificaciones push permiten enviar mensajes desde un servidor al dispositivo movil del usuario, apareciendo en la pantalla de bloqueo o barra de notificaciones.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es Flutter?',
    '{"a":"Un framework de Google para crear interfaces nativas multiplataforma con Dart","b":"Una base de datos de Google","c":"Un editor de codigo","d":"Un sistema operativo"}'::jsonb,
    'a', 'Flutter es un framework de UI de codigo abierto de Google que permite crear apps compiladas nativamente para movil, web y desktop desde un unico codigo base.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'junior', '¿Qué es una pantalla de splash?',
    '{"a":"Una pantalla de presentacion que aparece mientras la app carga","b":"Un tipo de gesto","c":"Un componente de navegacion","d":"Un metodo de autenticacion"}'::jsonb,
    'a', 'La pantalla de splash (o splash screen) es la primera pantalla que ve el usuario al abrir la app, mostrando el logo mientras se cargan los recursos iniciales.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué es el state management en Flutter?',
    '{"a":"Gestionar el estado de la app con patrones como BLoC, Provider o Riverpod","b":"Un tipo de base de datos","c":"El diseno de pantallas","d":"La conexion a internet"}'::jsonb,
    'a', 'State management en Flutter se refiere a como se comparte y actualiza el estado entre widgets, con patrones como BLoC, Provider, Riverpod y GetX.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué es la navegacion en React Native?',
    '{"a":"El sistema para moverse entre pantallas usando React Navigation o React Native Navigation","b":"Un tipo de animacion","c":"La conexion a la red","d":"Un componente de UI"}'::jsonb,
    'a', 'La navegacion en React Native maneja el flujo entre pantallas. React Navigation es la libreria mas popular, ofreciendo stack, tabs y drawer navigators.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué son los hooks en React Native?',
    '{"a":"Funciones que permiten usar estado y caracteristicas de React sin clases","b":"Ganchos para colgar el telefono","c":"Eventos tactiles","d":"Componentes nativos"}'::jsonb,
    'a', 'Los hooks (useState, useEffect, useContext) permiten usar el ciclo de vida y estado en componentes funcionales de React Native.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué es la persistencia offline en apps moviles?',
    '{"a":"Almacenar datos localmente para que la app funcione sin conexion","b":"Apagar el telefono","c":"Un tipo de sincronizacion","d":"La memoria cache del SO"}'::jsonb,
    'a', 'La persistencia offline permite que la app almacene y acceda a datos localmente (SQLite, Realm, AsyncStorage), sincronizando cuando hay conexion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué es el patron MVVM?',
    '{"a":"Model-View-ViewModel: separa la logica de negocio de la UI mediante un ViewModel","b":"Un tipo de base de datos","c":"Un metodo de animacion","d":"Un gesto tactil"}'::jsonb,
    'a', 'MVVM separa la interfaz (View) de la logica de negocio (Model) mediante un intermediario (ViewModel) que expone datos reactivos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué es la compilacion JIT en desarrollo movil?',
    '{"a":"Compilacion en tiempo de ejecucion que permite hot-reload durante el desarrollo","b":"Compilacion antes de ejecutar","c":"Un tipo de emulador","d":"Un metodo de depuracion"}'::jsonb,
    'a', 'JIT compilation permite recargar cambios en caliente (hot-reload) durante el desarrollo sin recompilar toda la app, acelerando el ciclo de desarrollo.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué es la accesibilidad en apps moviles?',
    '{"a":"Disenar apps que puedan ser usadas por personas con discapacidades","b":"El alcance de la app en tiendas","c":"La velocidad de carga","d":"La compatibilidad con versiones antiguas"}'::jsonb,
    'a', 'La accesibilidad movil incluye soporte para lectores de pantalla (TalkBack/VoiceOver), contraste suficiente, objetivos tactiles grandes y texto escalable.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'mid', '¿Qué es el consumo de APIs REST desde una app movil?',
    '{"a":"Hacer peticiones HTTP con fetch, axios o librerias nativas para obtener/enviar datos","b":"Una API de restaurante","c":"El menu de la app","d":"Un tipo de base de datos"}'::jsonb,
    'a', 'Las apps moviles consumen APIs REST mediante peticiones HTTP (GET, POST, PUT, DELETE) usando librerias como axios, fetch o URLSession.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es la arquitectura limpia (Clean Architecture)?',
    '{"a":"Separar el codigo en capas (presentacion, dominio, datos) con dependencias hacia adentro","b":"Escribir codigo sin comentarios","c":"Eliminar el codigo muerto","d":"Usar pocas lineas de codigo"}'::jsonb,
    'a', 'Clean Architecture organiza el codigo en capas independientes donde las capas internas (dominio) no dependen de las externas (frameworks, UI).'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es la inyeccion de dependencias en desarrollo movil?',
    '{"a":"Las dependencias se proporcionan desde fuera en lugar de crearlas internamente","b":"Una inyeccion de vacuna","c":"Un tipo de base de datos","d":"Un metodo de compilacion"}'::jsonb,
    'a', 'La inyeccion de dependencias (DI) mejora la testabilidad y modularidad al suministrar las dependencias de un objeto desde el exterior.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es el caching en apps moviles?',
    '{"a":"Almacenar respuestas de API localmente para evitar peticiones repetidas y mejorar velocidad","b":"La memoria RAM del dispositivo","c":"Un tipo de base de datos","d":"La eliminacion de datos"}'::jsonb,
    'a', 'El caching guarda datos de API en almacenamiento local para usarlos en peticiones posteriores, reduciendo la latencia y el consumo de datos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es la publicacion en Google Play Store?',
    '{"a":"Empaquetar, firmar y subir una app Android a la tienda oficial","b":"Descargar apps de Google","c":"Un tipo de prueba","d":"Un metodo de desarrollo"}'::jsonb,
    'a', 'Publicar en Google Play implica compilar la app en AAB/APK, firmarla con clave privada, crear ficha en Play Console y gestionar versiones.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es la optimizacion de rendimiento en apps moviles?',
    '{"a":"Tecnicas para reducir el uso de CPU, memoria y bateria, mejorando la fluidez","b":"Aumentar la resolucion de pantalla","c":"Agregar mas animaciones","d":"Usar mas hilos de ejecucion"}'::jsonb,
    'a', 'Optimizar rendimiento incluye reducir re-renderizados, lazy loading, comprimir imagenes, minimizar llamadas a API y liberar recursos no usados.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es App Thinning en iOS?',
    '{"a":"Optimizar el tamano de la app eliminando recursos no necesarios para el dispositivo","b":"Reducir el peso de la app","c":"Un tipo de compilacion","d":"Un metodo de testing"}'::jsonb,
    'a', 'App Thinning (Slicing, Bitcode, On-Demand Resources) reduce el tamano de descarga de apps iOS incluyendo solo los recursos necesarios.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es el testing en apps moviles?',
    '{"a":"Pruebas unitarias, de integracion, UI y E2E para garantizar calidad","b":"Usar la app normalmente","c":"Solo pruebas manuales","d":"Pruebas de carga"}'::jsonb,
    'a', 'El testing movil incluye pruebas unitarias (JUnit, XCTest), de widgets (Flutter), de integracion, UI (Detox, Espresso, XCUITest) y E2E.'),
  ((SELECT id FROM technical_areas WHERE name = 'Desarrollo Móvil'), 'senior', '¿Qué es la gestion de memoria en desarrollo movil?',
    '{"a":"Administrar la RAM para evitar fugas y optimizar el rendimiento","b":"La memoria del telefono","c":"El almacenamiento interno","d":"La tarjeta SD"}'::jsonb,
    'a', 'La gestion de memoria evita memory leaks liberando objetos no usados, usando weak references y optimizando el uso de RAM.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;

-- ─── Testing ───────────────────────────────────────────────────────

DO $$ BEGIN
  INSERT INTO quiz_questions (area_id, difficulty, question_text, options, correct_answer, explanation) VALUES
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es una prueba unitaria (unit test)?',
    '{"a":"Verifica el funcionamiento de una unidad individual de codigo","b":"Una prueba de todo el sistema","c":"Una prueba de la interfaz de usuario","d":"Una prueba de carga"}'::jsonb,
    'a', 'Las pruebas unitarias verifican componentes individuales del software de forma aislada, asegurando que cada parte funciona correctamente.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es Jest?',
    '{"a":"Un framework de testing para JavaScript con mocking y cobertura","b":"Una base de datos","c":"Un editor de codigo","d":"Un framework de frontend"}'::jsonb,
    'a', 'Jest es un framework de testing de JavaScript popular para React y Node.js, con funciones integradas de mocking, aserciones y cobertura.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es TDD (Test-Driven Development)?',
    '{"a":"Escribir pruebas antes del codigo de produccion","b":"Probar despues de escribir el codigo","c":"Un tipo de prueba manual","d":"Un marco de trabajo para pruebas"}'::jsonb,
    'a', 'TDD sigue el ciclo Red-Green-Refactor: escribir prueba que falla, escribir codigo minimo que la pasa, y refactorizar.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es una asercion (assertion) en testing?',
    '{"a":"Una expresion que verifica si una condicion es verdadera","b":"Una afirmacion sin comprobacion","c":"Un tipo de error","d":"Un archivo de configuracion"}'::jsonb,
    'a', 'Las aserciones comparan el resultado real con el esperado. Si la condicion falla, la prueba se marca como fallida.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es la cobertura de codigo?',
    '{"a":"Porcentaje del codigo ejecutado por las pruebas","b":"El numero total de pruebas","c":"La cantidad de lineas de codigo","d":"El tiempo de ejecucion"}'::jsonb,
    'a', 'La cobertura mide cuantas lineas, ramas o funciones del codigo son ejecutadas por las pruebas, ayudando a identificar codigo no probado.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es un mock en testing?',
    '{"a":"Un objeto simulado que imita el comportamiento de uno real para aislar la prueba","b":"Una burla o broma","c":"Un tipo de prueba","d":"Un archivo de configuracion"}'::jsonb,
    'a', 'Los mocks reemplazan dependencias reales con objetos simulados que devuelven respuestas controladas, permitiendo probar unidades de forma aislada.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es PyTest?',
    '{"a":"Un framework de testing para Python con sintaxis simple","b":"Una libreria de Python para web","c":"Una base de datos","d":"Un editor de codigo"}'::jsonb,
    'a', 'PyTest es el framework de testing mas popular para Python, con deteccion de tests, fixtures, parametrizacion y plugins.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'junior', '¿Qué es una prueba de regresion?',
    '{"a":"Verificar que cambios recientes no rompieron funcionalidades existentes","b":"Una prueba que retrocede","c":"Un tipo de prueba de carga","d":"Pruebas de la interfaz"}'::jsonb,
    'a', 'Las pruebas de regresion aseguran que nuevo codigo no introduzca errores en funcionalidades previamente existentes y probadas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'mid', '¿Qué es una prueba de integracion?',
    '{"a":"Verifica que multiples componentes o sistemas funcionen correctamente juntos","b":"Prueba un solo componente","c":"Prueba la interfaz de usuario","d":"Prueba el rendimiento"}'::jsonb,
    'a', 'Las pruebas de integracion verifican la interaccion entre diferentes modulos, servicios o sistemas, detectando problemas de comunicacion.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'mid', '¿Qué es Cypress?',
    '{"a":"Un framework de testing E2E con espera automatica y recarga en vivo","b":"Una base de datos","c":"Un editor de codigo","d":"Un lenguaje de programacion"}'::jsonb,
    'a', 'Cypress es un framework de testing E2E moderno que se ejecuta en el navegador, con recarga en tiempo real y espera automatica.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'mid', '¿Qué es el mocking de APIs?',
    '{"a":"Simular respuestas de APIs externas para probar sin depender de servicios reales","b":"Una API falsa","c":"Un tipo de servidor","d":"Una base de datos simulada"}'::jsonb,
    'a', 'Mocking de APIs intercepta peticiones HTTP y devuelve respuestas predefinidas, permitiendo probar sin conexion a servicios externos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'mid', '¿Qué es BDD (Behavior-Driven Development)?',
    '{"a":"Las pruebas se escriben en lenguaje natural comprensible por no tecnicos","b":"Desarrollo basado en comportamiento aleatorio","c":"Un tipo de testing manual","d":"Un framework de pruebas"}'::jsonb,
    'a', 'BDD extiende TDD describiendo el comportamiento esperado en lenguaje natural (Given-When-Then) usando herramientas como Cucumber o SpecFlow.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'mid', '¿Qué es una prueba E2E?',
    '{"a":"Prueba el flujo completo desde inicio a fin simulando un usuario real","b":"Prueba solo el backend","c":"Prueba solo el frontend","d":"Prueba unitaria de cada modulo"}'::jsonb,
    'a', 'Las pruebas E2E validan el sistema completo en un entorno que simula produccion, probando la interaccion entre todos los componentes.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'mid', '¿Qué es un stub en testing?',
    '{"a":"Un objeto que proporciona respuestas predefinidas a llamadas hechas durante la prueba","b":"Un tipo de error","c":"Un archivo de configuracion","d":"Un metodo de prueba"}'::jsonb,
    'a', 'Un stub es similar a un mock pero mas simple: solo proporciona valores fijos sin verificar como se llaman los metodos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'mid', '¿Qué es la prueba de humo (smoke test)?',
    '{"a":"Pruebas basicas rapidas para verificar funcionalidades principales","b":"Una prueba con humo","c":"Una prueba de rendimiento","d":"Un tipo de prueba unitaria"}'::jsonb,
    'a', 'Smoke tests son pruebas superficiales que verifican rapidamente que las funcionalidades criticas de la aplicacion no esten rotas.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es la prueba de carga (load testing)?',
    '{"a":"Evaluar el rendimiento del sistema bajo condiciones normales y pico de carga","b":"Una prueba con peso","c":"Un tipo de prueba unitaria","d":"Pruebas de interfaz"}'::jsonb,
    'a', 'El load testing mide como se comporta el sistema con multiples usuarios concurrentes, identificando cuellos de botella y limites de escalabilidad.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es k6?',
    '{"a":"Una herramienta de testing de carga con scripting en JavaScript","b":"Un numero hexadecimal","c":"Un tipo de base de datos","d":"Un framework de testing unitario"}'::jsonb,
    'a', 'k6 es una herramienta de load testing que permite simular trafico con scripts en JavaScript, midiendo rendimiento y estabilidad.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es el mutation testing?',
    '{"a":"Introducir cambios pequenos en el codigo para verificar que las pruebas los detectan","b":"Probar mutaciones geneticas","c":"Un tipo de prueba E2E","d":"Pruebas en multiples navegadores"}'::jsonb,
    'a', 'El mutation testing modifica deliberadamente el codigo (mutantes) y ejecuta las pruebas para medir su capacidad de detectar cambios.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es la piramide de testing?',
    '{"a":"Muchos tests unitarios, menos de integracion, pocos E2E","b":"Una jerarquia","c":"Un tipo de prueba","d":"Una herramienta"}'::jsonb,
    'a', 'La piramide de testing recomienda invertir principalmente en pruebas unitarias (base), seguidas de integracion y finalmente E2E (punta).'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es Playwright?',
    '{"a":"Un framework de testing E2E de Microsoft que automatiza navegadores con una API","b":"Un escritor de obras","c":"Un editor de codigo","d":"Una base de datos"}'::jsonb,
    'a', 'Playwright automatiza Chromium, Firefox y WebKit con una API unificada, ofreciendo esperas automaticas, interceptacion de red y testing movil.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es la integracion continua (CI) en testing?',
    '{"a":"Ejecutar automaticamente las pruebas en cada push para detectar errores rapido","b":"Integrar pruebas manualmente","c":"Un tipo de prueba","d":"Un metodo de desarrollo"}'::jsonb,
    'a', 'CI integra los cambios frecuentemente y ejecuta pruebas automaticamente, detectando errores temprano y manteniendo la calidad del codigo.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es la prueba de caja blanca?',
    '{"a":"Probar con conocimiento de la estructura interna y logica del codigo","b":"Probar sin conocer el codigo","c":"Una prueba visual","d":"Un tipo de testing E2E"}'::jsonb,
    'a', 'White-box testing disena casos basados en el conocimiento del codigo fuente, cubriendo caminos, condiciones y ciclos especificos.'),
  ((SELECT id FROM technical_areas WHERE name = 'Testing'), 'senior', '¿Qué es la prueba de caja negra?',
    '{"a":"Probar la funcionalidad sin conocer la implementacion interna, solo entradas y salidas","b":"Una prueba sin luz","c":"Probar el codigo fuente","d":"Un test de rendimiento"}'::jsonb,
    'a', 'Black-box testing evalua el software desde la perspectiva del usuario, probando que las entradas produzcan las salidas esperadas.')
  ON CONFLICT (area_id, question_text) DO NOTHING;
END $$;
